version: '3.8'

services:
  app:
    build: .
    container_name: llm_api
    command: llm_api
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./telegram_channels_data:/app/telegram_channels_data